-- Migration 013: Self-Activation Flag
-- Date: 2026-01-07
-- Purpose: Add flag to distinguish self-activation from admin invitations
--          Both use invite_token, but self-activation does NOT auto-approve
--
-- Run with: psql runsheet_db < backend/migrations/013_self_activation_flag.sql

BEGIN;

-- =============================================================================
-- SELF-ACTIVATION FLAG
-- =============================================================================

-- When true, the invite_token was generated by user self-registration
-- When false/null, it was sent by an admin (and will auto-approve on accept)
ALTER TABLE personnel ADD COLUMN IF NOT EXISTS is_self_activation BOOLEAN DEFAULT FALSE;

COMMIT;

-- =============================================================================
-- VERIFICATION
-- =============================================================================
-- Check column was added:
-- SELECT column_name, data_type, column_default 
-- FROM information_schema.columns 
-- WHERE table_name = 'personnel' AND column_name = 'is_self_activation';
